name: 4.0.$(Rev:r)

resources:
- repo: self

trigger:
- master

stages:
  - stage: test
    jobs:
      - job: run_tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: restore
              projects: '**/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              projects: '**/*.csproj'
              arguments: '--configuration Release'
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: test
              projects: 'test/**/*.csproj'
              arguments: '--configuration Release'
            
  - stage: publish
    jobs:
      - job: push_to_nuget
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              projects: '**/*.csproj'
              arguments: '--configuration Release'
          - task: DotNetCoreCLI@2
            displayName: 'DotNet Pack'
            inputs:
              command: pack
              packagesToPack: 'src/**/*.csproj'
              versioningScheme: byBuildNumber
              configuration: 'Release'     
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
          - task: NuGetCommand@2
            displayName: 'NuGet Push'
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: 'Public NuGet'