name: 0.0.0.$(Rev:r)

resources:
  - repo: self

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - /src
      - /test

stages:
  - stage: test
    jobs:
      - job: run_tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET 8"
            inputs:
              version: '8.0.x'
              packageType: sdk
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: build
              projects: 'test/**/*.csproj'
              arguments: '--configuration Release'
          - script: |
              dotnet tool update --global PowerShell --version 7.4.6
            displayName: 'Install PowerShell tool'
          - script: |
              pwsh test/${{ parameters.project }}/bin/Debug/net8.0/playwright.ps1 install-deps   
              pwsh test/${{ parameters.project }}/bin/Debug/net8.0/playwright.ps1 install   
            displayName: 'Download Playwright executable'
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: test
              projects: 'test/**/*.csproj'
              arguments: '--configuration Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish code coverage report'
            inputs:
              summaryFileLocation: '$(Agent.TempDirectory)/**/*.cobertura.xml'
