variables:
  - group: shared_buddy_variable_group

name: $(version).$(Rev:r)

resources:
  - repo: self

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.AspNetCore.Buddy.Pdf
      - /test/Adliance.AspNetCore.Buddy.Pdf.Test
      - pipeline-pdf.yml

stages:
  - template: pipeline-template-build-and-push.yml
    parameters:
      project: "src/Adliance.AspNetCore.Buddy.Pdf/*.csproj"
      testProject: "src/Adliance.AspNetCore.Buddy.Pdf.Test/*.csproj"
      nugetApiKey: "$(nuget_api_key)"
