variables:
  - group: shared_buddy_variable_group

name:  $(version).$(Rev:r)

resources:
  - repo: self

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.AspNetCore.Buddy.Email.AzureCommunicationServices

stages:
  - template: pipeline-template-build-and-push.yml
    parameters:
      project: "test/Adliance.AspNetCore.Buddy.Email.AzureCommunicationServices.Test/*.csproj"
      nugetApiKey: "$(nuget_api_key)"
      