variables:
  - template: pipeline-variables.yml

name: ${{ variables.version }}.$(Rev:r)

resources:
  - repo: self

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.AspNetCore.Buddy

stages:
  - stage: test
    jobs:
      - job: run_tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET"
            inputs:
              version: '8.0.x'
              packageType: sdk
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: test
              projects: 'test/Adliance.AspNetCore.Buddy.Test/*.csproj'
              arguments: '--configuration Release'
  
  - stage: publish
    jobs:
      - job: push_to_nuget
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET"
            inputs:
              version: '8.0.x'
              packageType: sdk
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              projects: 'src/Adliance.AspNetCore.Buddy/*.csproj'
              arguments: '--configuration Release'
          - task: DotNetCoreCLI@2
            displayName: 'Pack'
            inputs:
              command: pack
              packagesToPack: 'src/Adliance.AspNetCore.Buddy/*.csproj'
              versioningScheme: byBuildNumber
              configuration: 'Release'
              includeSymbols: true              
          - task: DotNetCoreCLI@2
            displayName: Push
            inputs:
              command: 'custom'
              custom: 'nuget'
              arguments: >
                push "$(Build.ArtifactStagingDirectory)/*.nupkg"
                --source "https://api.nuget.org/v3/index.json"
                --api-key "$(NUGET_API_KEY)"