variables:
  - template: pipeline-variables.yml

name: ${{ variables.version }}.$(Rev:r)

resources:
  - repo: self

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.AspNetCore.Buddy.Abstractions
      - /src/Adliance.AspNetCore.Buddy.Email.Mailjet
      - /test/Adliance.AspNetCore.Buddy.Email.Mailjet.Test
      - /pipeline-mailjet.yml

stages:
  - stage: test
    jobs:
      - job: run_tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: test
              projects: 'test/Adliance.AspNetCore.Buddy.Email.Mailjet.Test/*.csproj'
              arguments: '--configuration Release'

  - stage: publish
    jobs:
      - job: push_to_nuget
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'DotNet Pack'
            inputs:
              command: pack
              packagesToPack: 'src/Adliance.AspNetCore.Buddy.Email.Mailjet/*.csproj'
              versioningScheme: byBuildNumber
              configuration: 'Release'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
          - task: NuGetCommand@2
            displayName: 'NuGet Push'
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: 'Public NuGet'