variables:
  - group: shared_buddy_variable_group

name: 0.0.0.$(Rev:r)

resources:
  - repo: self

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - /src
      - /test
      - /pipeline-testsonly.yml

stages:
  - stage: test
    jobs:
      - job: run_tests
        variables:
          Adliance_Buddy_Tests__AzureStorageConnectionString: ${{ parameters.azureStorageConnectionString }}
        pool:
          vmImage: 'ubuntu-latest'
          
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET 8"
            inputs:
              version: '8.0.x'
              packageType: sdk
              
          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: build
              projects: 'test/**/*.csproj'
              arguments: '--configuration Release'
              
          - task: DotNetCoreCLI@2
            displayName: 'Lint'
            inputs:
              command: custom
              projects: 'Buddy.sln'
              custom: format
              arguments: '-v diag --verify-no-changes'
              
          - script: |
              dotnet tool update --global PowerShell --version 7.4.6
            displayName: 'Install PowerShell tool'
            
          - script: |
              pwsh test/Adliance.AspNetCore.Buddy.Testing.Test/bin/Release/net8.0/playwright.ps1 install-deps   
            displayName: 'Install Playwright dependencies'
            
          - script: |
              pwsh test/Adliance.AspNetCore.Buddy.Testing.Test/bin/Release/net8.0/playwright.ps1 install   
            displayName: 'Install Playwright executables'
            
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: test
              projects: 'test/**/*.csproj'
              arguments: '--configuration Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
              
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish code coverage report'
            inputs:
              summaryFileLocation: '$(Agent.TempDirectory)/**/*.cobertura.xml'
