variables:
  - template: pipeline-variables.yml
  - group: shared_buddy_variable_group

name: ${{ variables.version }}.$(Rev:r)

resources:
  - repo: self

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.AspNetCore.Buddy.Bulma

stages:
  - template: pipeline-template-build-and-push.yml
    parameters:
      project: 'src/Adliance.AspNetCore.Buddy.Bulma/*.csproj'    
      nugetApiKey: "${{ NUGET_API_KEY }}"
